### ISSUE TITLE
Support locale

### ISSUE THREAD

**Issue by potato4d** [potato4d/nuxt-dayjs-module#4]

**Comment by potato4d** [comment]
そもそも誰か locale 使ってるのかもわからん

**Comment by bart** [comment]
Same question here. Is there any i18n support for this nuxt module?

**Comment by potato4d** [comment]
@bart 
This module has just started supporting locale!
Please install v1.0.0 or higher.

**Comment by bart** [comment]
Awesome, thank you very much @potato4d !
